Category.create(title: "Baked goods")
Category.create(title: "Crafts and/or woodworking items")
Category.create(title: "Eggs")
Category.create(title: "Fresh and/or dried herbs")
Category.create(title: "Honey")
Category.create(title: "Maple syrup and/or maple products")
Category.create(title: "Nuts")
Category.create(title: "Poultry")
Category.create(title: "Soap and/or body care products")
Category.create(title: "Wine, beer, hard cider")
Category.create(title: "Dry beans")
Category.create(title: "Grains and or flour")
Category.create(title: "Mushrooms")
Category.create(title: "Tofu and or non-animal protein")
Category.create(title: "Cheese and/or dairy products")
Category.create(title: "Cut flowers")
Category.create(title: "Fish and/or seafood")
Category.create(title: "Fresh vegetables")
Category.create(title: "Canned or preserved fruits, vegetables, jams, jellies, preserves, salsas, pickles, dried fruit, etc.")
Category.create(title: "Meat")
Category.create(title: "Plants in containers")
Category.create(title: "Prepared foods (for immediate consumption)")
Category.create(title: "Trees, shrubs")
Category.create(title: "Coffee and or tea")
Category.create(title: "Fresh fruits")
Category.create(title: "Juices and or non-alcoholic ciders")
Category.create(title: "Pet food")
Category.create(title: "Wild harvested forest products: mushrooms, medicinal herbs, edible fruits and nuts, etc.")

